-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fightclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fightclub` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fightclub` ;

-- -----------------------------------------------------
-- Table `fightclub`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fightclub`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `empresa` VARCHAR(128) NULL,
  PRIMARY KEY (`id`));
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `fightclub`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fightclub`.`administrador` (
  `login` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`login`));


-- SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
